default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['USER'] %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  username: zxcv
  password: 12eQWEasd
  host: example-rails-app-with-angular-and-d3.cyq7b12nohlm.us-west-2.rds.amazonaws.com
  port: 5432
