default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ?-z7wQfN
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  username: db
  password: <%= ENV['DATABASE_PASSWORD'] %>
