# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed98b67482aa1c9b0e95a86045dfa3034eddc60db27344ce1eebd05a6c7c8ee52ac5249568fbfd9fc7ded0c05c0e447fe1c6479ec06c176d6c9972393ec1a382

test:
  secret_key_base: 3d82f035c2f87194cb0c827261b030c5cd6becec0c3497217608bbba51b21f5d6410fc5610a77fb1263a9bcaaa6e4a0c7ae60277c530f4e75ce9b6c1a8f61694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
